In [1]:
import pandas as pd
import numpy as np
from functions import *
import matplotlib.pyplot as plt

d = r'C:/Users/fabrizio/Documents/R_data/PROJECTS/MASTER/DATA/KKA Tirol NEU.xlsx'
data, trial = reader(d, 'Daten Tirol', header=18, test=False)

data.columns
tech_type=data[[1, 2,3,  4,5,6,7,8,9,10,11,12,13]]
bautyp=data[['mech.','biol. ','chem.']]

conditions_tech = [
    data[1] == 1,
    data[2] == 1,
    data[3] == 1, 
    data[4] == 1,
    data[5] == 1,
    data[6] == 1,
    data[7] == 1,
    data[8] == 1,
    data[9] == 1,
    data[10] == 1,
    data[11] == 1,
    data[12] == 1,
    data[13] == 1,
]


outcome_tech = [ '3-k', 'Bel.', 'SBR', 'MBR', 
                'Tropf','Rotation', 'Fest', 'Wirbel' ,
                'BKF', 'PKA','Filtersack', 'Kompost','Unbekannt']
data=logical_column(conditions_tech,outcome_tech,data,'tech_type')
conditions_bau = [
    data["mech."] == 'x',
    data["biol. "] == 'x',
    data["chem."] == 'x',
]

outcomes_bau = [
 "Mech", "Bio", "Chem"
]
data=logical_column(conditions_bau,outcomes_bau,data,'bautyp')

In [2]:
data=col_dropper(data,tech_type,bautyp)
data.dropna(how='all', axis=1,inplace=True)
data.dropna(how='all', axis=0,inplace=True)
data=data.fillna(0)

In [3]:
data[data.KG.isna()]

Empty DataFrame
Columns: [Unnamed: 0, Postzahl, Bezirk, Gemeinde, KG, Unnamed: 5, Bautyp, Unnamed: 7, Urkunde, Von, Bis, EW 60, m³/d, l/s, Lageplan, Anmerkungen, EW60 / m³/d, EW60 / l/s (10h), Unnamed: 35, KKA, Kl. KA, ?, tech_type, bautyp]
Index: []

[0 rows x 24 columns]

In [4]:
data=cleaner(data,['Unnamed: 0','Urkunde','Lageplan','Anmerkungen','Unnamed: 35', 'KKA', 'Kl. KA', '?'])

In [5]:
data.rename(columns={'Unnamed: 5':'KG_name','Unnamed: 7':'tech_detail'},inplace=True)

In [6]:
data.to_excel('output/tirol.xlsx',index=False)

In [7]:
data

,Postzahl,Bezirk,Gemeinde,KG,KG_name,Bautyp,tech_detail,Von,Bis,EW 60,m³/d,l/s,EW60 / m³/d,EW60 / l/s (10h),tech_type,bautyp
0,2/1623,Imst,70217,80009,Pitztal,Biologie,Pflanzenkläranlage (A =121m²),2014,2029,31,2.57,0,82.903226,0.0,PKA,Bio
1,2/2079,Imst,70210,80007,Mils bei Imst,Biologie,"3 Kammer Kläranlage (I = 3,5m³), bepflanzter B...",2013,2028,8,1.2,0.033,150.000000,356.4,PKA,Mech
2,2/1807,Imst,70207,80006,Karrösten,nicht bestimmt,"3 Kammer Faulanlage (I = 8m³), Pumpschacht, Pf...",2008,0,26.5,1.58,0,59.622642,0.0,PKA,Mech
3,2/1766,Imst,70221,80111,Stams,nicht bestimmt,Pflanzenkläranlage (A = 16m²),2007,0,5,0.75,0.02,150.000000,345.6,PKA,Mech
4,2/1625,Imst,70215,80106,Rietz,nicht bestimmt,"3 Kammer Kläranlage (I = 3 m³), Pflanzenbeet (...",2002,0,5,0.75,0,150.000000,0.0,PKA,Mech
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,9/796,Schwaz,70936,87011,Vomp,mech. Kläranlage,0,1958,0,?,?,?,0.000000,0.0,3-k,0
1290,9/762,Schwaz,70915,87110,Hart,mech. Kläranlage,3 Kammer Kläranlage,1956,0,?,?,?,0.000000,0.0,3-k,0
1291,9/764,Schwaz,70926,87007,Schwaz,mech. Kläranlage,3 Kammer Kläranlage,1956,0,?,?,?,0.000000,0.0,3-k,0
1292,9/750,Schwaz,70939,87014,Wiesing,mech. Kläranlage,3 Kammer Kläranlage,1955,0,10,0,0,0.000000,0.0,3-k,0
1293,9/703,Schwaz,70907,87003,Eben,mech. Kläranlage,3 Kammer Kläranlage,1951,0,?,?,?,0.000000,0.0,3-k,0